name: flutter_qr_code
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences:
  provider:
  http:
  flutter_native_splash: ^2.2.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  image: assets/images/splash screen.png
  color: "#22263F"

  assets:
    - assets/images/

flutter:
  uses-material-design: true
