// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5S3H9F3TaPi5Op-os_p8xO1Ew9yBnQLk',
    appId: '1:29341851160:web:e76c792b2db21e64fb2d6d',
    messagingSenderId: '29341851160',
    projectId: 'qr-code-c46ee',
    authDomain: 'qr-code-c46ee.firebaseapp.com',
    storageBucket: 'qr-code-c46ee.appspot.com',
    measurementId: 'G-R6B7EJ0L5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZBaMnunUa6CrTztJCtzbWX0oZpkEgngw',
    appId: '1:29341851160:android:3af30c0b0cadb545fb2d6d',
    messagingSenderId: '29341851160',
    projectId: 'qr-code-c46ee',
    storageBucket: 'qr-code-c46ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl5PeqQlw8sFckZ0Fjf1hp-XoVxuqnB0g',
    appId: '1:29341851160:ios:30e57ba77b1d0259fb2d6d',
    messagingSenderId: '29341851160',
    projectId: 'qr-code-c46ee',
    storageBucket: 'qr-code-c46ee.appspot.com',
    iosClientId: '29341851160-0jc1n1df01pmj1reg7518m1j5b6sn1g8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterQrCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl5PeqQlw8sFckZ0Fjf1hp-XoVxuqnB0g',
    appId: '1:29341851160:ios:30e57ba77b1d0259fb2d6d',
    messagingSenderId: '29341851160',
    projectId: 'qr-code-c46ee',
    storageBucket: 'qr-code-c46ee.appspot.com',
    iosClientId: '29341851160-0jc1n1df01pmj1reg7518m1j5b6sn1g8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterQrCode',
  );
}
